version = 0.1
[default.deploy.parameters]
stack_name = "irw-news-cms"
resolve_s3 = true
s3_prefix = "irw-news-cms"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
